### ISSUE TITLE
ee_as_raster

### ISSUE THREAD

**Issue by joshuarcarter** [shellstanton/accessibility#3]
Exporting NDVI surface from R to Google Drive using `ee_as_raster` (~line 120 Rmd) gives the following error:

The function does correctly save to Google Drive (files are present), error is initiated when importing from drive to local (seems to be a product of the function for which parameters can't be specified).

```Polling for task <id: OLV5YZB7RLEWVL32EN7QRW6G, time: 575s>.
State: COMPLETED
Moving image from Google Drive to Local ... Please wait  
File downloaded:
  * noid_image_2020_10_20_16_48_12_2020_10_20_16_48_13-0000000000-0000000000.tif
Saved locally as:
  * ./medNDVIaoi-0001.tif
File downloaded:
  * noid_image_2020_10_20_16_48_12_2020_10_20_16_48_13-0000032768-0000000000.tif
Saved locally as:
  * ./medNDVIaoi-0002.tif
File downloaded:
  * noid_image_2020_10_20_16_48_12_2020_10_20_16_48_13-0000065536-0000000000.tif
Saved locally as:
  * ./medNDVIaoi-0003.tif
Error in .local(.Object, ...) : 

Error in .rasterObjectFromFile(x, objecttype = "RasterBrick", ...) : 
  Cannot create a RasterLayer object from this file. (file does not exist)

**Comment by shellstanton** [comment]
This was due to some erroneous minus signs in the aoi specification I think, meaning that the resulting clipped image contained no data. I've updated this. The NDVI file took 705s to be generated using the ee_as_raster function, and was saved locally.

![image](https://user-images.githubusercontent.com/72806056/96702435-a5521780-1389-11eb-8486-318e72ff0696.png)
